# .readthedocs.yaml
# Read the Docs yapılandırma dosyası
# Ayrıntılar için https://docs.readthedocs.io/en/stable/config-file/v2.html sayfasına bakınız.

# Gerekli
version: 2

# Python ve ihtiyacınız olabilecek diğer araçların sürümlerini belirleyin
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Sphinx kullanarak docs/ dizininde belgeleri oluşturun
sphinx:
  configuration: docs/conf.py

# Yeniden üretilebilir yapılar sağlamak için bağımlılıklarınızı belirtmenizi öneririz:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt
